name: Terraform S3 Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ AKIASSJNMVJ2OORVOXML }}
          aws-secret-access-key: ${{ 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 }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
