name: Terraform S3 Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

  workflow_dispatch:

jobs:
  terraform:
    name: terraform Apply
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Setup terraform Cloud Token
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ secrets.TF_API_TOKEN }}"
              }
            }
          }
          EOF

      - name: terraform Init
        run: terraform init
     
      - name: terraform Validate
        run: terraform validate
     
    
      - name: terraform Apply
        run: terraform apply
        
